// Mocks generated by Mockito 5.4.6 from annotations
// in todo/test/data/datasources/todo_remote_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo/data/datasources/request/create_todo_request.dart' as _i5;
import 'package:todo/data/datasources/request/update_todo_request.dart' as _i6;
import 'package:todo/data/datasources/todo_api_service.dart' as _i3;
import 'package:todo/data/models/todo_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeTodoModel_0 extends _i1.SmartFake implements _i2.TodoModel {
  _FakeTodoModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoApiService extends _i1.Mock implements _i3.TodoApiService {
  MockTodoApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.TodoModel>> getTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getTodos, []),
            returnValue: _i4.Future<List<_i2.TodoModel>>.value(
              <_i2.TodoModel>[],
            ),
          )
          as _i4.Future<List<_i2.TodoModel>>);

  @override
  _i4.Future<_i2.TodoModel> getTodo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getTodo, [id]),
            returnValue: _i4.Future<_i2.TodoModel>.value(
              _FakeTodoModel_0(this, Invocation.method(#getTodo, [id])),
            ),
          )
          as _i4.Future<_i2.TodoModel>);

  @override
  _i4.Future<_i2.TodoModel> createTodo(_i5.CreateTodoRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#createTodo, [request]),
            returnValue: _i4.Future<_i2.TodoModel>.value(
              _FakeTodoModel_0(this, Invocation.method(#createTodo, [request])),
            ),
          )
          as _i4.Future<_i2.TodoModel>);

  @override
  _i4.Future<_i2.TodoModel> updateTodo(
    String? id,
    _i6.UpdateTodoRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodo, [id, request]),
            returnValue: _i4.Future<_i2.TodoModel>.value(
              _FakeTodoModel_0(
                this,
                Invocation.method(#updateTodo, [id, request]),
              ),
            ),
          )
          as _i4.Future<_i2.TodoModel>);

  @override
  _i4.Future<_i2.TodoModel> toggleTodo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleTodo, [id]),
            returnValue: _i4.Future<_i2.TodoModel>.value(
              _FakeTodoModel_0(this, Invocation.method(#toggleTodo, [id])),
            ),
          )
          as _i4.Future<_i2.TodoModel>);

  @override
  _i4.Future<void> deleteTodo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
