// Mocks generated by Mockito 5.4.6 from annotations
// in todo/test/data/repositories/todo_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todo/core/network/api_response.dart' as _i2;
import 'package:todo/core/network/network_info.dart' as _i7;
import 'package:todo/data/datasources/todo_local_datasource.dart' as _i3;
import 'package:todo/data/datasources/todo_remote_datasource.dart' as _i6;
import 'package:todo/data/models/todo_model.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResponse_0<T> extends _i1.SmartFake
    implements _i2.ApiResponse<T> {
  _FakeApiResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TodoLocalDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoLocalDatasource extends _i1.Mock
    implements _i3.TodoLocalDatasource {
  MockTodoLocalDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.TodoModel>> getTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getTodos, []),
            returnValue: _i4.Future<List<_i5.TodoModel>>.value(
              <_i5.TodoModel>[],
            ),
          )
          as _i4.Future<List<_i5.TodoModel>>);

  @override
  _i4.Future<void> saveTodos(List<_i5.TodoModel>? todos) =>
      (super.noSuchMethod(
            Invocation.method(#saveTodos, [todos]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [TodoRemoteDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTodoRemoteDatasource extends _i1.Mock
    implements _i6.TodoRemoteDatasource {
  MockTodoRemoteDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResponse<List<_i5.TodoModel>>> getTodos() =>
      (super.noSuchMethod(
            Invocation.method(#getTodos, []),
            returnValue: _i4.Future<_i2.ApiResponse<List<_i5.TodoModel>>>.value(
              _FakeApiResponse_0<List<_i5.TodoModel>>(
                this,
                Invocation.method(#getTodos, []),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<List<_i5.TodoModel>>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.TodoModel>> createTodo(
    String? title,
    String? description,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createTodo, [title, description]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.TodoModel>>.value(
              _FakeApiResponse_0<_i5.TodoModel>(
                this,
                Invocation.method(#createTodo, [title, description]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.TodoModel>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.TodoModel>> updateTodo(_i5.TodoModel? todo) =>
      (super.noSuchMethod(
            Invocation.method(#updateTodo, [todo]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.TodoModel>>.value(
              _FakeApiResponse_0<_i5.TodoModel>(
                this,
                Invocation.method(#updateTodo, [todo]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.TodoModel>>);

  @override
  _i4.Future<_i2.ApiResponse<_i5.TodoModel>> toggleTodo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#toggleTodo, [id]),
            returnValue: _i4.Future<_i2.ApiResponse<_i5.TodoModel>>.value(
              _FakeApiResponse_0<_i5.TodoModel>(
                this,
                Invocation.method(#toggleTodo, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<_i5.TodoModel>>);

  @override
  _i4.Future<_i2.ApiResponse<void>> deleteTodo(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTodo, [id]),
            returnValue: _i4.Future<_i2.ApiResponse<void>>.value(
              _FakeApiResponse_0<void>(
                this,
                Invocation.method(#deleteTodo, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResponse<void>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i7.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected =>
      (super.noSuchMethod(
            Invocation.getter(#isConnected),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
